name: Deploy

on:
  workflow_dispatch:      # permite ejecutarlo manualmente
  push:
    branches: [ main ]    # o cuando haya push a main (ajusta si quieres)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy placeholder (añade aquí tus pasos reales)"
