name: Deploy Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read   # OIDC no requerido en esta opción

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: camelscl-serving
  FUNCTION_NAME: camelscl-inference
  IMAGE_TAG: v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.lambda
          platforms: linux/amd64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          provenance: false
          sbom: false

      - name: Update Lambda
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          aws lambda update-function-code \
            --function-name "${{ env.FUNCTION_NAME }}" \
            --image-uri "$IMAGE_URI" \
            --region "${{ env.AWS_REGION }}"
          aws lambda wait function-updated --function-name "${{ env.FUNCTION_NAME }}" --region "${{ env.AWS_REGION }}"

      - name: Who am I?
        run: aws sts get-caller-identity
