name: Deploy Lambda (ECR image)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'models_release/**'
      - 'Dockerfile.lambda'
      - '.github/workflows/deploy.yml'
  workflow_dispatch: {}

permissions:
  id-token: write   # <- REQUIRED for OIDC
  contents: read

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: camelscl-serving
  FUNCTION_NAME: camelscl-inference
  IMAGE_TAG: v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   # <- MUST be set
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.lambda
          platforms: linux/amd64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          provenance: false
          sbom: false

      - name: Update Lambda to new image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          aws lambda update-function-code \
            --function-name "${{ env.FUNCTION_NAME }}" \
            --image-uri "$IMAGE_URI" \
            --region "${{ env.AWS_REGION }}"
          aws lambda wait function-updated --function-name "${{ env.FUNCTION_NAME }}" --region "${{ env.AWS_REGION }}"

      # Optional sanity check
      - name: Who am I?
        run: aws sts get-caller-identity
